// FIFA Weltmeisterschaft 2026 - Spieldaten
// Turniere in USA, Mexiko und Kanada

const teams = {
    'ARG': { name: 'Argentinien', flag: '🇦🇷' },
    'AUS': { name: 'Australien', flag: '🇦🇺' },
    'BEL': { name: 'Belgien', flag: '🇧🇪' },
    'BRA': { name: 'Brasilien', flag: '🇧🇷' },
    'CAN': { name: 'Kanada', flag: '🇨🇦' },
    'CHI': { name: 'Chile', flag: '🇨🇱' },
    'CHN': { name: 'China', flag: '🇨🇳' },
    'COL': { name: 'Kolumbien', flag: '🇨🇴' },
    'CRC': { name: 'Costa Rica', flag: '🇨🇷' },
    'CRO': { name: 'Kroatien', flag: '🇭🇷' },
    'CZE': { name: 'Tschechien', flag: '🇨🇿' },
    'DEN': { name: 'Dänemark', flag: '🇩🇰' },
    'ECU': { name: 'Ecuador', flag: '🇪🇨' },
    'EGY': { name: 'Ägypten', flag: '🇪🇬' },
    'ENG': { name: 'England', flag: '🏴󠁧󠁢󠁥󠁮󠁧󠁿' },
    'ESP': { name: 'Spanien', flag: '🇪🇸' },
    'FRA': { name: 'Frankreich', flag: '🇫🇷' },
    'GER': { name: 'Deutschland', flag: '🇩🇪' },
    'GHA': { name: 'Ghana', flag: '🇬🇭' },
    'GRE': { name: 'Griechenland', flag: '🇬🇷' },
    'HUN': { name: 'Ungarn', flag: '🇭🇺' },
    'IRN': { name: 'Iran', flag: '🇮🇷' },
    'ITA': { name: 'Italien', flag: '🇮🇹' },
    'JPN': { name: 'Japan', flag: '🇯🇵' },
    'KOR': { name: 'Südkorea', flag: '🇰🇷' },
    'MAR': { name: 'Marokko', flag: '🇲🇦' },
    'MEX': { name: 'Mexiko', flag: '🇲🇽' },
    'NED': { name: 'Niederlande', flag: '🇳🇱' },
    'NGA': { name: 'Nigeria', flag: '🇳🇬' },
    'NOR': { name: 'Norwegen', flag: '🇳🇴' },
    'NZL': { name: 'Neuseeland', flag: '🇳🇿' },
    'PER': { name: 'Peru', flag: '🇵🇪' },
    'POL': { name: 'Polen', flag: '🇵🇱' },
    'POR': { name: 'Portugal', flag: '🇵🇹' },
    'ROU': { name: 'Rumänien', flag: '🇷🇴' },
    'RUS': { name: 'Russland', flag: '🇷🇺' },
    'SAU': { name: 'Saudi-Arabien', flag: '🇸🇦' },
    'SEN': { name: 'Senegal', flag: '🇸🇳' },
    'SRB': { name: 'Serbien', flag: '🇷🇸' },
    'SVK': { name: 'Slowakei', flag: '🇸🇰' },
    'SWE': { name: 'Schweden', flag: '🇸🇪' },
    'SUI': { name: 'Schweiz', flag: '🇨🇭' },
    'THA': { name: 'Thailand', flag: '🇹🇭' },
    'TUN': { name: 'Tunesien', flag: '🇹🇳' },
    'TUR': { name: 'Türkei', flag: '🇹🇷' },
    'UKR': { name: 'Ukraine', flag: '🇺🇦' },
    'URY': { name: 'Uruguay', flag: '🇺🇾' },
    'USA': { name: 'USA', flag: '🇺🇸' },
    'VEN': { name: 'Venezuela', flag: '🇻🇪' },
};

const stadiums = {
    'MetLife': 'MetLife Stadium, New Jersey',
    'Dallas': 'AT&T Stadium, Dallas',
    'Kansas': 'Arrowhead Stadium, Kansas City',
    'Atlanta': 'Mercedes-Benz Stadium, Atlanta',
    'Miami': 'Hard Rock Stadium, Miami',
    'Houston': 'NRG Stadium, Houston',
    'Denver': 'Empower Field, Denver',
    'Seattle': 'Lumen Field, Seattle',
    'LA': 'SoFi Stadium, Los Angeles',
    'Vegas': 'Allegiant Stadium, Las Vegas',
    'Phoenix': 'State Farm Stadium, Phoenix',
    'Guadalajara': 'Estadio Jalisco, Guadalajara',
    'Mexico City': 'Estadio Azteca, Mexico City',
    'Monterrey': 'Estadio BBVA, Monterrey',
    'Toronto': 'BMO Field, Toronto',
    'Vancouver': 'BC Place, Vancouver',
};

const games = [
    // Group Stage - Beispielspiele (erweiterte Liste)
    {
        id: 1,
        stage: 'Gruppenphase',
        team1: 'ARG',
        team2: 'MEX',
        date: '2026-06-15',
        time: '14:00',
        stadium: 'MetLife',
        group: 'A'
    },
    {
        id: 2,
        stage: 'Gruppenphase',
        team1: 'FRA',
        team2: 'GER',
        date: '2026-06-15',
        time: '17:00',
        stadium: 'Dallas',
        group: 'A'
    },
    {
        id: 3,
        stage: 'Gruppenphase',
        team1: 'BRA',
        team2: 'CAN',
        date: '2026-06-16',
        time: '14:00',
        stadium: 'Kansas',
        group: 'B'
    },
    {
        id: 4,
        stage: 'Gruppenphase',
        team1: 'ENG',
        team2: 'ESP',
        date: '2026-06-16',
        time: '17:00',
        stadium: 'Atlanta',
        group: 'B'
    },
    {
        id: 5,
        stage: 'Gruppenphase',
        team1: 'USA',
        team2: 'NED',
        date: '2026-06-17',
        time: '20:00',
        stadium: 'LA',
        group: 'C'
    },
    {
        id: 6,
        stage: 'Gruppenphase',
        team1: 'BEL',
        team2: 'SRB',
        date: '2026-06-17',
        time: '17:00',
        stadium: 'Miami',
        group: 'C'
    },
    {
        id: 7,
        stage: 'Gruppenphase',
        team1: 'POR',
        team2: 'POL',
        date: '2026-06-18',
        time: '14:00',
        stadium: 'Houston',
        group: 'D'
    },
    {
        id: 8,
        stage: 'Gruppenphase',
        team1: 'ITA',
        team2: 'URY',
        date: '2026-06-18',
        time: '17:00',
        stadium: 'Denver',
        group: 'D'
    },
    {
        id: 9,
        stage: 'Gruppenphase',
        team1: 'AUS',
        team2: 'JPN',
        date: '2026-06-19',
        time: '14:00',
        stadium: 'Seattle',
        group: 'E'
    },
    {
        id: 10,
        stage: 'Gruppenphase',
        team1: 'MAR',
        team2: 'CRO',
        date: '2026-06-19',
        time: '17:00',
        stadium: 'Vegas',
        group: 'E'
    },
    {
        id: 11,
        stage: 'Gruppenphase',
        team1: 'MEX',
        team2: 'POL',
        date: '2026-06-22',
        time: '14:00',
        stadium: 'Mexico City',
        group: 'A'
    },
    {
        id: 12,
        stage: 'Gruppenphase',
        team1: 'ARG',
        team2: 'FRA',
        date: '2026-06-22',
        time: '17:00',
        stadium: 'Guadalajara',
        group: 'A'
    },
    {
        id: 13,
        stage: 'Gruppenphase',
        team1: 'CAN',
        team2: 'ESP',
        date: '2026-06-23',
        time: '14:00',
        stadium: 'Monterrey',
        group: 'B'
    },
    {
        id: 14,
        stage: 'Gruppenphase',
        team1: 'BRA',
        team2: 'ENG',
        date: '2026-06-23',
        time: '17:00',
        stadium: 'Toronto',
        group: 'B'
    },
    {
        id: 15,
        stage: 'Gruppenphase',
        team1: 'NED',
        team2: 'SEN',
        date: '2026-06-24',
        time: '14:00',
        stadium: 'Vancouver',
        group: 'C'
    },
    {
        id: 16,
        stage: 'Gruppenphase',
        team1: 'USA',
        team2: 'IRN',
        date: '2026-06-24',
        time: '17:00',
        stadium: 'Phoenix',
        group: 'C'
    },
    {
        id: 17,
        stage: 'Achtelfinale',
        team1: 'ARG',
        team2: 'AUS',
        date: '2026-07-01',
        time: '14:00',
        stadium: 'MetLife',
    },
    {
        id: 18,
        stage: 'Achtelfinale',
        team1: 'FRA',
        team2: 'NED',
        date: '2026-07-02',
        time: '17:00',
        stadium: 'Dallas',
    },
    {
        id: 19,
        stage: 'Viertelfinale',
        team1: 'ARG',
        team2: 'FRA',
        date: '2026-07-09',
        time: '17:00',
        stadium: 'Kansas',
    },
    {
        id: 20,
        stage: 'Semifinale',
        team1: 'ARG',
        team2: 'FRA',
        date: '2026-07-14',
        time: '20:00',
        stadium: 'MetLife',
    },
    {
        id: 21,
        stage: 'Finale',
        team1: 'ARG',
        team2: 'BRA',
        date: '2026-07-19',
        time: '19:00',
        stadium: 'MetLife',
    },
];